### ISSUE TITLE
Click Test code on first IDE scrolls to next IDE

### ISSUE THREAD

**Issue by willkessler** [terminalcloud/udacity-integration-demo#1]
If two IDEs are on the page at once, clicking test code on the top one scrolls to the terminal in the second one (probably a focus() call).  This shouldn't happen.

**Comment by reem** [comment]
Fixed.

**Comment by reem** [comment]
https://github.com/terminalcloud/web-terminal/commit/4f29890f77b1bfd8c104b38b91256617814ec891
