### ISSUE TITLE
Second terminal is too low, too much whitespace

### ISSUE THREAD

**Issue by willkessler** [terminalcloud/udacity-integration-demo#10]
Simply solved by making it `top:700px`

See attached shots

As it is now:

![image](https://cloud.githubusercontent.com/assets/176268/21121986/685a315c-c084-11e6-8136-68c14ee0c2d2.png)

Corrected:

![image](https://cloud.githubusercontent.com/assets/176268/21121981/5a6f7d54-c084-11e6-9a46-c0ca6f4c618c.png)

**Comment by natomato** [comment]
fixed with: 1518ce07c43b5b95a81fbe23d42659f6546c2b09

**Comment by willkessler** [comment]
Fixed! LGTM
