### ISSUE TITLE
Should be possible to have multiple REPLs on a page, each with their own tab, so that they don't overwrite each other

### ISSUE THREAD

**Issue by willkessler** [terminalcloud/udacity-integration-demo#4]
And we can use one machine for the entire page.

**Comment by reem** [comment]
Fixed https://github.com/terminalcloud/udacity-integration-demo/commit/ecdf3c40faa634368400955f9bac45b0b2d5df74

**Comment by willkessler** [comment]
Reopening, not really addressed

**Comment by reem** [comment]
Re-fixed.

**Comment by willkessler** [comment]
LGTM, thanks!
