### ISSUE TITLE
Text in REPL cut off

### ISSUE THREAD

**Issue by willkessler** [terminalcloud/udacity-integration-demo#5]
Probably a padding issue

![image](https://cloud.githubusercontent.com/assets/176268/21116292/ea668fda-c069-11e6-9afa-a996f02c39a9.png)

**Comment by reem** [comment]
This is because the two terminals are not the same size

**Comment by natomato** [comment]
cool, i test putting the terminal only window at the same size then.

**Comment by natomato** [comment]
Here's a possible solution with padding-left
![screen shot 2016-12-12 at 5 28 48 pm](https://cloud.githubusercontent.com/assets/778135/21123918/9c0cff14-c090-11e6-82d9-c2fd5c730bbb.png)

**Comment by natomato** [comment]
fixed with this commit: 77975d341d4550dd3ed4ce0717a63b92c4a869e6
